version: '3.4'

services:
  apache:
    image: 'php:7.2-apache'
    container_name: php
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    links:
      - db
  db:
    container_name: db-mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    ports: 
      - "3306:3306"
    volumes:
    - /var/lib/mysql
    - ./dump:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_ROOT_PASSWORD=root